[I 161208 21:27:22 server:569] Starting backend server
[I 161208 21:27:22 server:570] MongoDB URI: mongodb://mongo-1:27017
[I 161208 21:27:22 server:594] Web server is waiting for requests...
[I 161208 21:27:22 server:525] Cleaning up old source images older than 7 days from database...
[I 161208 21:27:22 server:545] Database cleanup complete
[I 161208 21:27:41 server:57] xxx
[I 161208 21:27:41 server:59] yyy
[E 161208 21:27:41 web:1548] Uncaught exception GET /other (172.17.0.1)
    HTTPServerRequest(protocol='http', host='localhost', method='GET', uri='/other', version='HTTP/1.1', remote_ip='172.17.0.1', headers={'Authorization': 'Basic dGVzdHVzZXI6dGltZcSbd29yaw==', 'Accept-Language': 'cs,en-GB;q=0.8,en;q=0.6,en-AU;q=0.4', 'Host': 'localhost', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36', 'Connection': 'keep-alive', 'Upgrade-Insecure-Requests': '1', 'If-None-Match': '"c0df7408a8538ef931befbaff0cb5139b62f2c3c"', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, sdch, br'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/site-packages/tornado/web.py", line 1467, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "./server.py", line 117, in newFunc
        authenticatedUser = auth(userToken, password)
      File "./server.py", line 62, in verify_password
        logging.info('usertologing ' + user_entry['username'])
    TypeError: 'Future' object is not subscriptable
[E 161208 21:27:41 web:1971] 500 GET /other (172.17.0.1) 3.63ms
